name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npm run migration:generate"
dev = "npm run migration:migrate && npm exec remix vite:dev"
