# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ec9e14e5a3e1d4d66a897f1dc5d608da"
application_url = "https://olympics-yield-beginning-dx.trycloudflare.com"
embedded = true
name = "Custom Banner"
handle = "custom-banner-63"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_themes"

[auth]
redirect_urls = [
  "https://olympics-yield-beginning-dx.trycloudflare.com/auth/callback",
  "https://olympics-yield-beginning-dx.trycloudflare.com/auth/shopify/callback",
  "https://olympics-yield-beginning-dx.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "hexsis-test-store.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
