# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ec9e14e5a3e1d4d66a897f1dc5d608da"
application_url = "https://custombanner.ishaf.info"
embedded = true
name = "Custom Banner"
handle = "custom-banner-63"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hexsis-test-store.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products,read_online_store_pages,unauthenticated_read_content"

[auth]
redirect_urls = [
  "https://custombanner.ishaf.info/auth/callback",
  "https://custombanner.ishaf.info/auth/shopify/callback",
  "https://custombanner.ishaf.info/api/auth/callback"
]

[pos]
embedded = false
